baseURL = "https://rennus.me/"
languageCode = 'en-us'
title = "Rennan's Blog"
theme = 'PaperMod'

[params]
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  # Home page info section
  [params.homeInfoParams]
    Title = "Hi, I'm Rennan! 👋"
    Content = """
Welcome to my blog! I'm a passionate developer who loves sharing insights about technology, programming, and digital experiences.

Here you'll find my thoughts on software development, tutorials, and explorations into the latest tech trends. Whether you're a fellow developer or just curious about the digital world, I hope you'll find something valuable here.

Feel free to explore my posts and connect with me!
"""

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    identifier = 'tags'
    name = 'Tags'
    url = '/tags/'
    weight = 30
  [[menu.main]]
    identifier = 'categories'
    name = 'Categories'
    url = '/categories/'
    weight = 40
